# Generated by Django 6.0.5 on 2026-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('activation', 'Account Activation'), ('topup', 'Wallet Top Up'), ('investment', 'Investment'), ('game', 'Game Entry')], max_length=20),
        ),
    ]
