# Generated by Django 6.0.5 on 2026-05-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
