# Generated by Django 6.0.5 on 2026-05-21 21:28

import aviator.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AviatorRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_point', models.FloatField(default=aviator.models.generate_crash_point)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('flying', 'Flying'), ('crashed', 'Crashed')], default='waiting', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('crashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AviatorBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto_cashout', models.FloatField(blank=True, null=True)),
                ('cashout_multiplier', models.FloatField(blank=True, null=True)),
                ('winnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashed_out_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aviator_bets', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='aviator.aviatorround')),
            ],
        ),
    ]
