# Generated by Django 6.0.5 on 2026-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviatorround',
            old_name='crashed_at',
            new_name='betting_ends_at',
        ),
        migrations.RenameField(
            model_name='aviatorround',
            old_name='started_at',
            new_name='flying_ends_at',
        ),
        migrations.AlterField(
            model_name='aviatorround',
            name='status',
            field=models.CharField(choices=[('betting', 'Betting'), ('flying', 'Flying'), ('crashed', 'Crashed')], default='betting', max_length=10),
        ),
    ]
